name: Podbijanie wersji

on:
  push:
    branches:
      - main

# Uprawnienia do zapisu w repo, potrzebne przy pushu:
permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Pozostaje zalogowany w Gicie dla kolejnych kroków

      - name: Konfiguracja Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalowanie zależności
        run: npm install

      - name: Konfiguracja Gita
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commitowanie niezacommitowanych zmian
        run: |
          git add package.json package-lock.json
          git commit -m "(Bot GitHub Action): Ustawiam wersje na 0.0.0" || echo "Brak zmian do commitowania"

      - name: Podbijanie wersji
        run: |
          npm version patch -m "(Bot GitHub Action): podbicie wersji do ---> %s"

      - name: Wypchnięcie zmian
        run: git push origin main --follow-tags
